name: nucleus_one_exporter
description: A sample command-line application.
version: 1.0.0
homepage: https://www.ademero.com

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: any
  characters: any
  # cli_util: any
  cli_util:
    git:
      url: https://github.com/jibbers42/cli_util
      ref: stderr-use-ansi-color
  collection: any
  dartx: any
  fpdart: any
  freezed_annotation: any
  get_it: any
  http: any
  meta: any
  nucleus_one_dart_sdk:
    path: ../nucleus_one_dart_sdk
  path: any
  quiver: any
  rxdart: any
  storagebox: any
  tuple: any

dev_dependencies:
  build_runner: any
  freezed: any
  glados: any
  lints: any
  mocktail: any
  test: any

# dependency_overrides:
