name: nucleus_one_exporter
description: A sample command-line application.
version: 1.0.0
homepage: https://www.ademero.com

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: any
  characters: any
  collection: any
  dartx: any
  dartz: any
  get_it: any
  meta: any
  nucleus_one_dart_sdk:
    path: ../nucleus_one_dart_sdk
  path: any
  quiver: any
  storagebox: any

dev_dependencies:
  # glados: any
  glados:
    git:
      url: https://github.com/jibbers42/glados
      ref: update-deps
      path: glados
  lints: any
  mocktail: any
  test: any

# dependency_overrides:
