name: Build and release - Linux

on:
  workflow_run:
    workflows: "Build and release - Windows"
    types: completed

jobs:
  build-and-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the previous workflow succeeded
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo ${MOST_RECENT_TAG}
          sudo apt-get update
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      - id: installFlutter
        run: |
          mkdir ~/dev
          cd ~/dev
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
          /bin/bash -c "yes | flutter doctor --android-licenses"
      
      - id: buildExporter
        run: |
          export PATH="$PATH:~/dev/flutter/bin"
          cd ${GITHUB_WORKSPACE}
          flutter build linux --release
      
      - name: Compress output to ZIP file
        run: |
          ls -R build/linux
          zip -r -DestinationPath build/linux/runner/Release/$env:OUTPUT_BINARIES_NAME build/linux/runner/Release
      
      - name: Create GitHub release draft
        uses: softprops/action-gh-release@v1
        with:
          # draft: true
          tag_name: ${{ env.MOST_RECENT_TAG }}
          files: |
            ./build/windows/runner/Release/${{ env.OUTPUT_BINARIES_NAME }}
          fail_on_unmatched_files: true