# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Binaries - Windows

on:
  push:
    branches: [ "wip/create-install" ]
  pull_request:
    branches: [ "wip/create-install" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - run: |
          flutter config --enable-windows-desktop
          flutter build windows
      
      # Set the WiX path.  See https://github.com/orgs/community/discussions/27149
      # - name: Set path for candle and light
      #   run: $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
      
      - name: Find light 1
        run: (get-command light.exe).Path
      
      - run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Find light 2
        run: (get-command light.exe).Path