# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Binaries - Windows

on:
  push:
    branches: [ "wip/create-install" ]
  pull_request:
    branches: [ "wip/create-install" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - run: |
          flutter config --enable-windows-desktop
          flutter build windows
      
      # Set the WiX path.  See https://www.scivision.dev/github-actions-path-append/
      - name: Add WiX path to GITHUB_PATH
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - id: buildExporter
        run: |
          cd \
          md dev
          cd dev
          export PATH="$PATH:`pwd`/flutter/bin"
          git clone https://github.com/AdemeroIncPub/nucleus_one_exporter.git
          cd nucleus_one_exporter
          flutter build windows --release
      
      - name: Build MSI
        run: |
          candle.exe -nologo "install\windows\Setup.wxs" -out "install\windows\Setup.wixobj" -ext WixUIExtension
          light.exe -nologo "install\windows\Setup.wixobj" -out "install\windows\Setup.msi"  -ext WixUIExtension